services:
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=capellax
      - MONGO_INITDB_ROOT_PASSWORD=123456
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=capellax
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: always
